### ISSUE TITLE
Error deploy vercel

### ISSUE THREAD

**Issue by fiqryq** [theodorusclarence/notiolink#32]
halo mas , i can't deploy to vercel using repo that i fork from you, any suggestions? 

error : 

<img width="1085" alt="Screen Shot 2022-02-09 at 14 54 31" src="https://user-images.githubusercontent.com/25787603/153146110-a40386e3-9322-487e-91ee-6e3f36ba4896.png">

**Comment by theodorusclarence** [comment]
have you add the correct env? because the error message says that the database id is not found

**Comment by theodorusclarence** [comment]
Nice, thanks for using Notiolink!
