### ISSUE TITLE
May I ask a question about environmental variables?

### ISSUE THREAD

**Issue by wumaorg** [theodorusclarence/notiolink#45]
Excuse me, why did I enter text that did not contain a hyphen, and why did I automatically add a hyphen when deploying, resulting in deployment failure?

Do you have this problem in vercel?

<img width="696" alt="image" src="https://user-images.githubusercontent.com/6800487/182031993-ae6843ab-4bfc-4d8c-aa31-6043a4be4c7c.png">

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/6800487/182031856-1859527b-ea19-4582-bf8c-4939e2b9bf4f.png">

**Comment by theodorusclarence** [comment]
> why did I enter text that did not contain a hyphen, and why did I automatically add a hyphen when deploying, resulting in deployment failure?

It's auto-hyphenated by the notion library, so there's nothing wrong with the database id.

I suspect it's about the integration permission. Maybe try checking your integration sharing on the **specific notion page**

![image](https://user-images.githubusercontent.com/55318172/182135507-226b5e44-e0b9-4a97-8e7a-1247df81d90b.png)

**Comment by wumaorg** [comment]
> > why did I enter text that did not contain a hyphen, and why did I automatically add a hyphen when deploying, resulting in deployment failure?
> 
> It's auto-hyphenated by the notion library, so there's nothing wrong with the database id.
> 
> I suspect it's about the integration permission. Maybe try checking your integration sharing on the **specific notion page**
> 
> ![image](https://user-images.githubusercontent.com/55318172/182135507-226b5e44-e0b9-4a97-8e7a-1247df81d90b.png)

I'm sorry. That's exactly the problem.

**Comment by theodorusclarence** [comment]
Nice! Hope you enjoy using notiolink 😄
